### ISSUE TITLE
Via Rail is nicknamed Via Rail train de Charlevoix

### ISSUE THREAD

**Issue by nekohayo** [transitland/transitland-atlas#1024]
There might be an error in the metadata for Via Rail. In https://github.com/transitland/transitland-atlas/blob/main/feeds/viarail.ca.dmfr.json I can see `"id": "f-f-viarail~traindecharlevoix"`, `"onestop_id": "o-f2m-traindecharlevoix"`, etc. but [Via Rail](https://en.wikipedia.org/wiki/Via_Rail) is Canada-wide, whereas [Charlevoix](https://en.wikipedia.org/wiki/Charlevoix) is just one tiny county region (where Via presumably has a stop, but there are [many](https://www.viarail.ca/en/plan/faq/plan-your-trip/where-can-i-find-addresses-location-maps-via-rails-stations) stops/stations out there).

I just thought it was weird when seeing it in [this Transitous MR diff](https://github.com/public-transport/transitous/pull/58/files) (c.c. @mlundblad & @jbruechert in case this does end up changing in transitland-atlas).

**Comment by drewda** [comment]
Onestop IDs for feeds and operators are designed to be globally unique. However, they are not meant to be exact descriptions of a service.

Transitland sometimes uses automated means to create Onestop IDs and sometimes it's manually created. This particular feed Onestop ID was probably created by one of the earlier generation of automated approaches that assess what information was in the GTFS feed at the time. It may not be the ideal ID today, but we typically err on the side of stability, rather than changing IDs.

For more information, see https://www.transit.land/documentation/concepts/onestop-id-scheme
