### ISSUE TITLE
How to add feed?

### ISSUE THREAD

**Issue by kylebarron** [transitland/transitland-atlas#28]
Hey, Transitland is an amazing product! I made a [web visualization](https://all-transit.com) and someone on Reddit mentioned missing GTFS feeds: 

- Corpus Christi, TX: https://www.ccrta.org/gtfs-feed/
- Omaha, NE: https://iowa-gtfs.com/ (not sure if this is an official source)

I see that you're transitioning from v1 to v2. Is there a way I can add new feeds to this repository?

**Comment by drewda** [comment]
@kylebarron thanks for the kind words and your interest.

All feed records for both v1 and v2 are now managed by this repository. You are welcome to open a pull request that adds new feed records.

We are overdue to add documentation on how to do this. In the meantime, please give a try following these instructions:

1. duplicate an existing DMFR file under the feeds directory; title your new file with the hostname of the GTFS feed you are adding
2. add the appropriate URL
3. propose a new Onestop ID for the feed; this can now be a "two-part" Onestop ID, which begins with `f-` and continues with a unique string, like the transit operator's name; use `~` instead of spaces or other punctionation in the name component
4. add license and/or authorization metadata if you are aware of it
5. open a PR
6. GitHub Actions (continuous integration service) will run a basic validation check on your PR
