### ISSUE TITLE
Inaccurate region designations

### ISSUE THREAD

**Issue by ivyrze** [transitland/transitland-atlas#740]
The auto-linked location data for the [Detroit People Mover](https://www.transit.land/operators/o-dpsby4-detroitpeoplemover) is inaccurate. It lists Ontario, Canada as a served region, but that’s not the case. I’m guessing this is because the alignment goes very close to the Detroit River and thus the U.S.-Canada border, but nonetheless it does not cross the border and only serves downtown Detroit.

**Comment by drewda** [comment]
Transitland uses [1:10m scale country and state boundaries from the Natural Earth project](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/). The boundaries are somewhat coarse, so it's probably not capturing the exact boundary between Detroit and Windsor.

One of the ways Transitland handles this uncertainty is by matching against multiple geographies, so that's why you'll still see Detroit People Mover listed under https://www.transit.land/operators?city_name=Detroit&adm1_name=Michigan&adm0_name=United%20States%20of%20America even as it's also listed under https://www.transit.land/operators?adm1_name=Ontario&adm0_name=Canada

Hope this context helps.
